"""Init migrations.

Revision ID: 31a2c8b45b46
Revises: 
Create Date: 2025-12-19 23:24:23.860757+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a2c8b45b46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_stats',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('completed_jobs', sa.Integer(), nullable=False),
    sa.Column('failed_jobs', sa.Integer(), nullable=False),
    sa.Column('cancelled_jobs', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('total_storage_used', sa.BigInteger(), nullable=False),
    sa.Column('average_file_size', sa.Float(), nullable=False),
    sa.Column('average_processing_time', sa.Float(), nullable=False),
    sa.Column('average_queue_time', sa.Float(), nullable=False),
    sa.Column('most_popular_operation', sa.String(length=32), nullable=True),
    sa.Column('operation_counts', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='valid_month'),
    sa.CheckConstraint('year >= 2020', name='valid_year'),
    sa.PrimaryKeyConstraint('year', 'month')
    )
    op.create_index('ix_monthly_stats_year_month', 'monthly_stats', ['year', 'month'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_file_size', sa.BigInteger(), nullable=False),
    sa.Column('max_daily_jobs', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('daily_job_count', sa.Integer(), nullable=False),
    sa.Column('daily_job_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('storage_quota', sa.BigInteger(), nullable=True),
    sa.Column('storage_used', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('max_daily_jobs >= 0', name='max_daily_jobs_non_negative'),
    sa.CheckConstraint('max_file_size > 0', name='max_file_size_positive'),
    sa.CheckConstraint('storage_quota >= 0', name='storage_quota_non_negative'),
    sa.CheckConstraint('storage_used >= 0', name='storage_used_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index('ix_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('requests_per_day', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.BigInteger(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('daily_request_count', sa.Integer(), nullable=False),
    sa.Column('request_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('daily_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('can_upload', sa.Boolean(), nullable=False),
    sa.Column('can_download', sa.Boolean(), nullable=False),
    sa.Column('can_list_jobs', sa.Boolean(), nullable=False),
    sa.Column('can_delete_jobs', sa.Boolean(), nullable=False),
    sa.Column('max_file_size', sa.BigInteger(), nullable=False),
    sa.Column('ip_whitelist', sa.JSON(), nullable=True),
    sa.Column('user_agent_restriction', sa.Text(), nullable=True),
    sa.CheckConstraint('max_file_size > 0', name='api_key_max_file_size_positive'),
    sa.CheckConstraint('requests_per_minute > 0', name='requests_per_minute_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_keys_created_at', 'api_keys', ['created_at'], unique=False)
    op.create_index('ix_api_keys_expires_at', 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_index('ix_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('input_path', sa.String(length=1024), nullable=False),
    sa.Column('output_path', sa.String(length=1024), nullable=True),
    sa.Column('operation', sa.Enum('CONVERT', 'TRIM', 'NORMALIZE', 'EXTRACT_AUDIO', 'MERGE', 'ADD_EFFECTS', 'COMPRESS', 'SPECTROGRAM', 'CONCATENATE', 'REVERSE', 'CHANGE_SPEED', 'CHANGE_PITCH', name='operation_type'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADED', 'DOWNLOADING', 'PROCESSING', 'UPLOADING', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED', name='job_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('codec', sa.String(length=32), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('last_downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('queue_time', sa.Float(), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.CheckConstraint('file_size > 0', name='file_size_positive'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='progress_range'),
    sa.CheckConstraint('retry_count >= 0', name='retry_count_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('ix_jobs_expires_at', 'jobs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_index('ix_jobs_operation', 'jobs', ['operation'], unique=False)
    op.create_index('ix_jobs_user_created', 'jobs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_index('ix_jobs_user_status', 'jobs', ['user_id', 'status'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index('ix_system_logs_created_at_desc', 'system_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_system_logs_job_id', 'system_logs', ['job_id'], unique=False)
    op.create_index('ix_system_logs_level_component', 'system_logs', ['level', 'component'], unique=False)
    op.create_index('ix_system_logs_user_id', 'system_logs', ['user_id'], unique=False)
    op.create_table('failed_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_failed_jobs_error_type', 'failed_jobs', ['error_type'], unique=False)
    op.create_index('ix_failed_jobs_failed_at', 'failed_jobs', ['failed_at'], unique=False)
    op.create_index('ix_failed_jobs_job_id', 'failed_jobs', ['job_id'], unique=False)
    op.create_index('ix_failed_jobs_resolved', 'failed_jobs', ['resolved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_failed_jobs_resolved', table_name='failed_jobs')
    op.drop_index('ix_failed_jobs_job_id', table_name='failed_jobs')
    op.drop_index('ix_failed_jobs_failed_at', table_name='failed_jobs')
    op.drop_index('ix_failed_jobs_error_type', table_name='failed_jobs')
    op.drop_table('failed_jobs')
    op.drop_index('ix_system_logs_user_id', table_name='system_logs')
    op.drop_index('ix_system_logs_level_component', table_name='system_logs')
    op.drop_index('ix_system_logs_job_id', table_name='system_logs')
    op.drop_index('ix_system_logs_created_at_desc', table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index('ix_jobs_user_status', table_name='jobs')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index('ix_jobs_user_created', table_name='jobs')
    op.drop_index('ix_jobs_operation', table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index('ix_jobs_expires_at', table_name='jobs')
    op.drop_index('ix_jobs_created_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_api_keys_user_id', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index('ix_api_keys_expires_at', table_name='api_keys')
    op.drop_index('ix_api_keys_created_at', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_users_username_lower', table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_monthly_stats_year_month', table_name='monthly_stats')
    op.drop_table('monthly_stats')
    # ### end Alembic commands ###