events {}
http {
    upstream api { server api:8000; }
    server {
        listen 80;
        server_name localhost;
        client_max_body_size 500M;

        location / {
            proxy_pass http://api;
            proxy_set_header Host $host;
        }

        location /flower/ {
            # No Auth for local development
            rewrite ^/flower/(.*)$ /$1 break;
            proxy_pass http://flower:5555;
        }
    }
}